### ekf config file ###
ekf_node:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    publish_acceleration: false
    publish_tf: true
    two_d_mode: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /odom
    odom0_config: [false, false, false,
                  false, false, false,
                  true, true, false,
                  false, false, true,
                  false, false, false]


    imu0: /demo/imu
    imu0_config: [false, false, false,   # position
                  false, false, false,   # orientation (OFF)
                  false, false, false,   # linear velocity
                  false, false, true,    # angular velocity z (yaw rate)
                  false, false, false]   # linear acceleration