### ekf config file ###
ukf_filter_node:
  ros__parameters:
    use_sim_time: false
    frequency: 30.0
    publish_acceleration: false
    sensor_timeout: 0.1
    publish_tf: false
    two_d_mode: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    
    pose0: /uwb/odom             # <-- UWB pose topic
    pose0_config: [true, true, true,    # x, y position
                   false, false, false,    # yaw orientation
                   false, false, false,   # no velocities
                   false, false, false,
                   false, false, false]

    process_noise_covariance: [1.0, 1.0, 0.0,
                               0.0,  0.0,  1.0,
                               0.0,  0.0,  0.0]  # example for x, y, yaw

    initial_pose_covariance: [1.0, 1.0, 0.0,
                              0.0, 0.0, 1.0,
                              0.0, 0.0, 0.0]